#!/usr/bin/env python3

import sys

import rospy

import map_data as md


def main():
    rospy.init_node('tester_node')

    path = sys.path[0]

    map_data = md.MapData(path + "/../data/buchlovice_1.gpx")
    map_data.run_queries()
    map_data.run_parse()
    map_data.save_to_pickle()

    while not rospy.is_shutdown():
        pass

if __name__ == "__main__":
    main()
