#!/usr/bin/env python3

import path_planner as pa
import sys

import map_data as md

import rospy


def main():
    rospy.init_node('tester_node')

    path = sys.path[0]

    '''path_analyzer = pa.PathAnalysis(path + "/../data/coords.gpx")

    path_analyzer.run_standalone("test_file.gpx")'''

    map_data = md.MapData(path + "/../data/buchlovice_1.gpx")
    map_data.run_queries()
    map_data.run_parse()


    while not rospy.is_shutdown():
        pass

if __name__ == "__main__":
    main()
