#!/usr/bin/env python

import matplotlib.pyplot as plt
import pickle
import sys

from vis_utils import plot_map, save_map, plot_footways_plan


if __name__ == "__main__":
    path = sys.path[0]

    file_name = "buchlovice_1.mapdata"
    save_map_data = False
    save_bgd = False
    if len(sys.argv) > 1:
        if "-f" in sys.argv:
            file_name = sys.argv[sys.argv.index("-f") + 1]
        if "-sm" in sys.argv:
            save_map_data = True
        if "-sb" in sys.argv:
            save_bgd = True

    with open(path + "/../data/" + file_name, "rb") as fh:
        map_data = pickle.load(fh)

    plot_map(map_data, save_bgd)
    if save_map_data:
        save_map(path + "/../data/map.png")
    plt.show()

    plot_footways_plan(map_data)
    plt.show()
